---

- job:
    name: build-images-x86_64/asahi/build-fex-rootfs
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/asahi/build-fex-rootfs"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/cloud/base/build-aws
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-aws"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/cloud/base/build-azure
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-azure"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/cloud/base/build-gcp
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-gcp"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/cloud/base/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/cloud/base/build-uefi-uki
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-uefi-uki"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/container/base/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/container/base/build-generic-init
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic-init"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/container/base/build-generic-minimal
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic-minimal"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/container/toolbox/build-toolbox
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/toolbox/build-toolbox"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/desktop/kde/build-desktop-disk
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/kde/build-desktop-disk"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/desktop/kde/build-desktop-live
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/kde/build-desktop-live"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/desktop/workstation/build-disk
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/workstation/build-disk"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/desktop/workstation/build-live
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/workstation/build-live"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/server/guest/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/server/guest/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/server/host/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/server/host/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/vagrant/base/build-libvirt
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/vagrant/base/build-libvirt"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/vagrant/base/build-virtualbox
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/vagrant/base/build-virtualbox"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-x86_64/wsl/build
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/wsl/build"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: x86_64
- job:
    name: build-images-aarch64/asahi/build-fex-rootfs
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/asahi/build-fex-rootfs"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/cloud/base/build-aws
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-aws"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/cloud/base/build-azure
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-azure"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/cloud/base/build-gcp
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-gcp"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/cloud/base/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/cloud/base/build-uefi-uki
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/cloud/base/build-uefi-uki"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/container/base/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/container/base/build-generic-init
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic-init"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/container/base/build-generic-minimal
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/base/build-generic-minimal"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/container/toolbox/build-toolbox
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/container/toolbox/build-toolbox"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/desktop/kde/build-desktop-disk
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/kde/build-desktop-disk"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/desktop/kde/build-desktop-live
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/kde/build-desktop-live"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/desktop/workstation/build-disk
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/workstation/build-disk"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/desktop/workstation/build-live
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/desktop/workstation/build-live"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/server/guest/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/server/guest/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/server/host/build-generic
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/server/host/build-generic"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/vagrant/base/build-libvirt
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/vagrant/base/build-libvirt"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/vagrant/base/build-virtualbox
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/vagrant/base/build-virtualbox"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64
- job:
    name: build-images-aarch64/wsl/build
    parent: tmt-test
    vars:
      tmt_url: "https://pagure.io/{{ zuul.project.name }}"
      tmt_ref: "{{ zuul.ref }}"
      tmt_plan: "/tmt/plans/wsl/build"
      distro: fedora-rawhide
      compose: Fedora-latest
      tf_arch: aarch64

- project:
   check:
    jobs:

      - build-images-x86_64/asahi/build-fex-rootfs
      - build-images-x86_64/cloud/base/build-aws
      - build-images-x86_64/cloud/base/build-azure
      - build-images-x86_64/cloud/base/build-gcp
      - build-images-x86_64/cloud/base/build-generic
      - build-images-x86_64/cloud/base/build-uefi-uki
      - build-images-x86_64/container/base/build-generic
      - build-images-x86_64/container/base/build-generic-init
      - build-images-x86_64/container/base/build-generic-minimal
      - build-images-x86_64/container/toolbox/build-toolbox
      - build-images-x86_64/desktop/kde/build-desktop-disk
      - build-images-x86_64/desktop/kde/build-desktop-live
      - build-images-x86_64/desktop/workstation/build-disk
      - build-images-x86_64/desktop/workstation/build-live
      - build-images-x86_64/server/guest/build-generic
      - build-images-x86_64/server/host/build-generic
      - build-images-x86_64/vagrant/base/build-libvirt
      - build-images-x86_64/vagrant/base/build-virtualbox
      - build-images-x86_64/wsl/build
      - build-images-aarch64/asahi/build-fex-rootfs
      - build-images-aarch64/cloud/base/build-aws
      - build-images-aarch64/cloud/base/build-azure
      - build-images-aarch64/cloud/base/build-gcp
      - build-images-aarch64/cloud/base/build-generic
      - build-images-aarch64/cloud/base/build-uefi-uki
      - build-images-aarch64/container/base/build-generic
      - build-images-aarch64/container/base/build-generic-init
      - build-images-aarch64/container/base/build-generic-minimal
      - build-images-aarch64/container/toolbox/build-toolbox
      - build-images-aarch64/desktop/kde/build-desktop-disk
      - build-images-aarch64/desktop/kde/build-desktop-live
      - build-images-aarch64/desktop/workstation/build-disk
      - build-images-aarch64/desktop/workstation/build-live
      - build-images-aarch64/server/guest/build-generic
      - build-images-aarch64/server/host/build-generic
      - build-images-aarch64/vagrant/base/build-libvirt
      - build-images-aarch64/vagrant/base/build-virtualbox
      - build-images-aarch64/wsl/build
